### ISSUE TITLE
Compatible with Python 3.*?

### ISSUE THREAD

**Issue by codeagencybe** [cytex124/odoo-automatic-backup#12]
Hello,

Does this app works with Python 3 and upwards on Odoo 11.0 Enterprise?

**Comment by cytex124** [comment]
Hi,

Thx for the question.

It is tested on Python3.6. Because I´m only using the normal features of Python3, it should work on Python 3.5+. (odoo11 needs Python3.5+)
It works also on the enterprise edition.

I will added it into the readme and description-html.

Best regards,

Andy

**Comment by cytex124** [comment]
Today I will release a new version. There you will find the "works with" section
