### ISSUE TITLE
Add Backblaze B2 backup storage? 

### ISSUE THREAD

**Issue by codeagencybe** [cytex124/odoo-automatic-backup#13]
Is it possible to add Backblaze B2 cloud storage as new storage provider? 
In my opinion, they have the best pricing for cold storage (0,005$/GB/month) and is even a lot cheaper than Amazon S3. 

https://www.backblaze.com/b2/cloud-storage.html
https://www.backblaze.com/b2/cloud-storage-pricing.html

API docs: https://www.backblaze.com/b2/docs/

**Comment by cytex124** [comment]
Hey,

In Germany Backblaze B2 isn´t really popular or a big thing. So there was no need. 
I will check it on the weekend. 

But number1 priority are bugs. So ... I ask for understanding :).

Best regards,

Andy

**Comment by codeagencybe** [comment]
Hello Andy,

Sure, no problem. Bugfixing is important. 
Backblaze is pretty big and famous around the world, especially in the market of the business backups and NAS backups, especially with Synology and Arq they are quite strong. 
And they have the best and most simple pricing available.

So I think it could be very good improvement of your app.

**Comment by cytex124** [comment]
Hi,

today I released a new version. Just pull it. It includes Backblaze B2 Cloud Storage support. Hope you like it.

Best regards,

Andy
