### ISSUE TITLE
Module breaks Odoo 11 (Community&Enterprise) when pasted in addons folder

### ISSUE THREAD

**Issue by rogerv95** [cytex124/odoo-automatic-backup#15]
When I paste the module to the addons folder odoo performs well, after first server reboot odoo stops working well. Database selector shows as corrupted page, some icons and images stop working and show broken link icon and if material/united theme is installed apps background and some other featrues stop working. After reboot first time loading the page usually gives 500 error and second time goes to corrupted database page.
<img width="1129" alt="captura de pantalla 2018-03-26 a les 23 25 00" src="https://user-images.githubusercontent.com/28661848/37934787-b602fb68-314f-11e8-843f-055d9aa0078d.png">
After removing it from the addons folder everything works well again.

I checked dependencies&updated everything and performed several new installations from scratch (New Ubuntu server VM+new odoo install)
Another odoo backup module (auto_backup) is having the same issue and other people is giving information on the related issue on it's github page. 
https://github.com/Yenthe666/auto_backup/issues/96
I'm pasting it here because I just found out that I had the same issue with this module.

**Comment by cytex124** [comment]
Hi,

please show me your stacktrace. There has to be a error. 
Also please tell me:
1. any other custom modules?
2. installed all dependencies from requirements.txt?
3. the addon folder looks like this? odoo/addons/automatic_backup_to_whatever/initfile... 

Best regards,

Andy

**Comment by rogerv95** [comment]
**1.any other custom modules?**
Tried with other custom modules and alone happens both ways.
**2.installed all dependencies from requirements.txt?**
Yes
**3.the addon folder looks like this? odoo/addons/automatic_backup_to_whatever/initfile...**
Addon folder is: /odoo/custom/addons/auto_backup/

I don't have a stacktrace or log file right now because I've been trying with different setups and configurations and I deleted the VM from the server. I will setup a fresh install tonight with the addon and get the log file.

**Comment by cytex124** [comment]
Can you also post your configuration file?

**Comment by cytex124** [comment]
No answer - No Problem

**Comment by drinktea0808** [comment]
hi. i am having the exact same issue too. 

here is my config file

[options] 
; This is the password that allows database operations:
admin_passwd = admin
db_host = vvv.xcxcxcxcxcxc.ap-southeast-1.rds.amazonaws.com
db_port = 5432
db_user = odoo
db_password = xcxcxcxcxcxc
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/odoo-server/addons,/odoo/custom/addons
dbfilter=^%h$
limit_time_cpu=600
limit_time_real=1200
