### ISSUE TITLE
Does it work with option list_db = False?

### ISSUE THREAD

**Issue by alysonbg** [cytex124/odoo-automatic-backup#21]
Hello,
I am trying to set up your module with my odoo 11 community edition. I want to make backups on my owncloud server, but I would like disable the option list_db. Is this possible?

**Comment by cytex124** [comment]
why don´t u try it and give me the answer?
Normally list_db doesn´t effect the module.

**Comment by alysonbg** [comment]
Actually I tried and I received an error messaging saying that I did not have permission to do that action.

I have already moved on to another solution, so I am sorry, but I don't have neither a print screen or error message in order to show to you the exactly problem.

If you want, you can close this issue.
