### ISSUE TITLE
Internal Server Error in Odoo 11 CE

### ISSUE THREAD

**Issue by wshamasneh** [cytex124/odoo-automatic-backup#6]
After Installing all of the requirements and placing the application in the Addon folder, cannot run Odoo giving the following error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by cytex124** [comment]
can you please post the stacktrace?

**Comment by cytex124** [comment]
Sorry have to close the issue. If you don't post the stack trance I really can't help you. Please open a new issue If u have still problems to install this module.
